
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"

[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  framework = "vite"
  functions = "netlify/functions"
  command = "npm run dev"
  targetPort = 5173

[build.environment]
  NODE_ENV = "production"
  NODE_VERSION = "20"
  CI = "false"

[functions]
  node_bundler = "zisi"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200