[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  framework = "create-react-app"
  functions = "netlify/functions"
  command = "npm run dev"
  targetPort = 5173

[build.environment]
  NODE_ENV = "production"
  CI = "false"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
