import image1       from '../assets/imagen1.webp'
import image2       from '../assets/imagen2.webp'
import image3       from '../assets/imagen3.webp'
import image4       from '../assets/imagen4.webp'
import casaclub1    from '../assets/casaclub1.webp'
import casaclub2    from '../assets/casaclub2.webp'
import casaclub3    from '../assets/casaclub3.webp'
import casaclub4    from '../assets/casaclub4.webp'
import casaclub5    from '../assets/casaclub5.webp'
import rosavento1   from '../assets/rosavento1.webp'
import rosavento3   from '../assets/rosavento3.webp'
import rosavento4   from '../assets/rosavento4.webp'
import rosavento5   from '../assets/rosavento5.webp'
import rosenda1     from '../assets/rosenda1.webp'
import rosenda3     from '../assets/rosenda3.webp'
import rosenda4     from '../assets/rosenda4.webp'
import terravento1  from '../assets/terravento1.webp'
import terravento2  from '../assets/terravento2.webp'
import terravento3  from '../assets/terravento3.webp'
import terravento4  from '../assets/terravento4.webp'

export default [image1,image2,image3,image4, casaclub1, casaclub2, casaclub3, casaclub4, casaclub5, rosavento1, rosavento3, rosavento4, rosavento5, rosenda1, rosenda3, rosenda4, terravento1, terravento2, terravento3, terravento4]